In [1]:
import torch
import numpy as np

In [4]:
torch.__version__

'2.6.0+cu124'

## 从list到tensor

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

## 从numpy到tensor

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7703, 0.3391],
        [0.4825, 0.2506]]) 



## tensor的shape

In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3105, 0.7823, 0.5260],
        [0.8618, 0.1118, 0.5509]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
shape = (2,3,2,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[[0.1334, 0.2560],
         [0.6349, 0.0515],
         [0.0133, 0.2189]],

        [[0.7591, 0.5672],
         [0.2404, 0.1951],
         [0.7650, 0.0650]]]) 

Ones Tensor: 
 tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])


## tensor的属性

In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor | tensor的shape: {tensor.shape}")
print(f"Datatype of tensor | tensor的数据类型: {tensor.dtype}")
print(f"Device tensor is stored on| tensor使用的设备: {tensor.device}")


Shape of tensor | tensor的shape: torch.Size([3, 4])
Datatype of tensor | tensor的数据类型: torch.float32
Device tensor is stored on| tensor使用的设备: cpu
Device tensor is stored on| tensor使用的设备: cuda:0


## 把tensor放到gpu

In [41]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
print(f"Device tensor is stored on| tensor使用的设备: {tensor.device}")

Device tensor is stored on| tensor使用的设备: cuda:0


## tensor的基本操作

- 默认情况下，张量是在 CPU 上创建的。我们需要使用 .to 方法（在检查加速器可用性后）
- 如果您熟悉 NumPy API，您会发现 Tensor API 使用起来轻而易举。

### 标准的类似 numpy 的索引和切片：

In [15]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [28]:
tensor=torch.tensor([
    [1.,1.,10.],
    [2.,2.,20.],
    [3.,3.,30.]
])
print(f"First row: {tensor[0]}")
print(f"First col: {tensor[:,0]}")
print(f"Last column: {tensor[:, -1]}")
print(f"Shape: {tensor.shape}")

First row: tensor([ 1.,  1., 10.])
First col: tensor([1., 2., 3.])
Last column: tensor([10., 20., 30.])
Shape: torch.Size([3, 3])


### cat
dim参数指定沿哪个dim拼接

In [24]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[ 1,  1, 10,  1,  1, 10,  1,  1, 10],
        [ 2,  2, 20,  2,  2, 20,  2,  2, 20],
        [ 3,  3, 30,  3,  3, 30,  3,  3, 30]])


### Arithmetic operations  算术运算

In [29]:
y1 = tensor @ tensor.T
y1
# @就是matmul，矩阵乘法

tensor([[102., 204., 306.],
        [204., 408., 612.],
        [306., 612., 918.]])

In [35]:
y3=torch.zeros_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
y3

tensor([[102., 204., 306.],
        [204., 408., 612.],
        [306., 612., 918.]])

In [36]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[  1.,   1., 100.],
        [  4.,   4., 400.],
        [  9.,   9., 900.]])

### 单元素张量
Single-element tensors If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():
单元素张量如果您有一个单元素张量，例如通过将张量的所有值聚合为一个值，则可以使用 item（） 将其转换为 Python 数值：

In [39]:
agg = tensor.sum()
print(f"agg : {agg},{type(agg)}")
agg_item = agg.item()
print(agg_item, type(agg_item))

agg : 72.0,<class 'torch.Tensor'>
72.0 <class 'float'>


### In-place operations 原位操作
将结果存储到作数中的作称为就地调用。它们由 _ 后缀表示。例如：x.copy_（y） 、x.t_（） 将更改 x。

**就地作可以节省一些内存，但在计算派生数时可能会出现问题，因为会立即丢失历史记录。因此，不鼓励使用它们。**

In [40]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[ 1.,  1., 10.],
        [ 2.,  2., 20.],
        [ 3.,  3., 30.]]) 

tensor([[ 6.,  6., 15.],
        [ 7.,  7., 25.],
        [ 8.,  8., 35.]])


### Bridge with NumPy  使用 NumPy 桥接

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.
存储在cpu上的tensor可以和numpy数组共享内存，改变一个将改变另一个。这就称为桥接。

In [42]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [43]:
t.add_(1.5)
print(f"t: {t}")

print(f"n: {n}")

t: tensor([2.5000, 2.5000, 2.5000, 2.5000, 2.5000])
n: [2.5 2.5 2.5 2.5 2.5]


In [44]:
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
