In [1]:
import torch
import numpy as np

In [4]:
torch.__version__

'2.6.0+cu124'

## 从list到tensor

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

## 从numpy到tensor

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7703, 0.3391],
        [0.4825, 0.2506]]) 



## tensor的shape

In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3105, 0.7823, 0.5260],
        [0.8618, 0.1118, 0.5509]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
shape = (2,3,2,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[[0.1334, 0.2560],
         [0.6349, 0.0515],
         [0.0133, 0.2189]],

        [[0.7591, 0.5672],
         [0.2404, 0.1951],
         [0.7650, 0.0650]]]) 

Ones Tensor: 
 tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])


## tensor的属性

In [14]:
tensor = torch.rand(3,4)

print(f"Shape of tensor | tensor的shape: {tensor.shape}")
print(f"Datatype of tensor | tensor的数据类型: {tensor.dtype}")
print(f"Device tensor is stored on| tensor使用的设备: {tensor.device}")
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
print(f"Device tensor is stored on| tensor使用的设备: {tensor.device}")

Shape of tensor | tensor的shape: torch.Size([3, 4])
Datatype of tensor | tensor的数据类型: torch.float32
Device tensor is stored on| tensor使用的设备: cpu
Device tensor is stored on| tensor使用的设备: cuda:0


## tensor的基本操作