# numpy基础

[参考链接](https://itimor.github.io/ml/mllib/)

In [1]:
import numpy as np

In [9]:

sh=(2,3,1)
a=np.ones(sh)
a

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

a,b共享内存，同步改变

In [16]:
b=a.reshape((6,))
b
a[0][0][0]=123.
a,b

(array([[[123.],
         [  1.],
         [  1.]],
 
        [[  1.],
         [  1.],
         [  1.]]]),
 array([123.,   1.,   1.,   1.,   1.,   1.]))